server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecuritydb?serverTimezone=GMT%2B8
    username: root
    password: chen123
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml